### ISSUE TITLE
CompileProvider

### ISSUE THREAD

**Issue by kumavis** [MetaMask/provider-engine#10]
https://github.com/ethereum/mist/blob/3e8b9dc7ec3b641eb6cff02d43acd82f9a4b0d9c/modules/ipc/ipcProviderBackend.js#L399-L417

**Comment by axic** [comment]
Perhaps this is done with https://github.com/MetaMask/provider-engine/pull/47? Or is it planned to support Serpent? (LLL? Mutan? :) )

**Comment by kumavis** [comment]
ill leave it open for comment
