### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/provider-engine#110]
Right now the `rpc-subprovider` conditionally requires the `xhr` or `request` modules depending on the context, but it does not import a react-native solution in *that* context.

If we found a react-native compatible module that exposed a `request` compatible API, we could swap it in conditionally, and support React Native very easily.

**Comment by flyswatter** [comment]
That didn't fully do it yet.

**Comment by joost-xyz** [comment]
Can't wait to use this module in RN

**Comment by flyswatter** [comment]
@joost-xyz actually this should be working in React-Native now, using the `fetch` subprovider!  Try it out!

Closing for now, because I'm 99% sure this works.

**Comment by srameshr** [comment]
@danfinlay 
Does it work? Is there a working example of how to use this in react native?

**Comment by danfinlay** [comment]
Yes, it works, just use the `fetch` subprovider. In fact, `zero.js` should now work with RN, just try it.

**Comment by srameshr** [comment]
@danfinlay Like how do I try it? How do I make sure that its a part of RN project? How do I invoke it?

**Comment by danfinlay** [comment]
The [readme](https://github.com/MetaMask/provider-engine/blob/master/README.md) shows a sample usage of the provider-engine library. It's a pretty simple library, if you need to use it, it could be use reading [the source code](https://github.com/MetaMask/provider-engine/blob/master/index.js) to understand how it stacks middlewares together.
