### ISSUE TITLE
Nonce does not increment

### ISSUE THREAD

**Issue by Recmo** [MetaMask/provider-engine#115]
(Using the example from README.md, with the `HookedWalletSubprovider` callbacks implemented)

The first transactions always succeeds. Subsequent transactions fail because the nonce is not incremented.

**Comment by LogvinovLeon** [comment]
I think it's because of EIP55. Some ethereum addreses counld be checksumed and contain mixed case letters and therefore one address can have two values in `nonceCache` object.

```
JSON.stringify(web3.currentProvider._providers[3].nonceCache)

{
"0x1078291bBcc539F51559F14BC57D1575D3801DF8":"0x7",
"0x1078291bbcc539f51559f14bc57d1575d3801df8":"0x08"
}
```
