### ISSUE TITLE
Feature Request: Dynamic Polling Interval

### ISSUE THREAD

**Issue by hitchcott** [MetaMask/provider-engine#124]
Different chains have different block-times, with Kovan, it's a consistent 4 seconds, so polling should probably be around slightly less than 4s mark. For PoW chains with non-consistent 10-25 second times, a 4s block time makes more sense, but it might be overkill some chains future EVM chains that have longer blocktimes, and underkill for others. 

This can be set manually, sure, perhaps there could be an option, on init (and maybe ever x blocks), to sample the last 5 blocks to determine the average block time, and then (re)set a suitable polling interval dynamically.

**Comment by kumavis** [comment]
yep, makes sense. we're working on breaking out the block polling entirely in our in-progress provider-engine rewrite.

some stuff:
https://github.com/kumavis/json-rpc-engine
https://github.com/kumavis/eth-block-tracker

**Comment by hitchcott** [comment]
Great, I'll keep track. On a related note, I think an option to disable polling entirely would be nice, as some apps don't really care about being in sync until user initiates some action (I tried using `_getFirstBlock` instead of `start`, but this seems to break filters. (I guess this might be what you're getting by separating those two libraries).

**Comment by kumavis** [comment]
you should be able to call `start()` then `stop()` right away

**Comment by kumavis** [comment]
adding block polling to provider-engine was a fundamental mistake i made with this module.
i've started work on a more composable rewrite here:
https://github.com/kumavis/json-rpc-engine
https://github.com/MetaMask/eth-json-rpc-middleware
https://github.com/kumavis/eth-json-rpc-filters

**Comment by kumavis** [comment]
@hitchcott btw you can specify blockTracker pollingInterval via `opts.pollingInterval`

**Comment by aukhan-akru** [comment]
@kumavis did you remove block polling from web3-provider-engine ??

**Comment by mcmire** [comment]
@aukhan-akru Yes, see: https://github.com/MetaMask/web3-provider-engine/blob/main/CHANGELOG.md#1200
