### ISSUE TITLE
Uncompiled ES6

### ISSUE THREAD

**Issue by gagarin55** [MetaMask/provider-engine#127]
I'm using create-react-app tool, when I try to use web3-privider-engine I receive errors during the build.
I've described issue there https://github.com/facebookincubator/create-react-app/issues/1907

The problem is that you provide some uncompiled ES6 modules. Could you give me please some advice how to resolve it.

**Comment by gagarin55** [comment]
After this https://github.com/MetaMask/provider-engine/blob/master/package.json#L18 I even can't run it ;( Why you don't provide compiled npm packages ? ;(

**Comment by Moejoe90** [comment]
I am facing exactly the same issue, have you managed to fix this?

**Comment by flyswatter** [comment]
Possible solutions to this:

1. We remove ES7 from eth-block-tracker
2. We declare we are now strictly ES7, and you need to transpile your project using something like `babel`.
3. Eth-block-tracker could include transpiling in its build process, and we export that instead.

Looks like we're going to start looking at a better pattern for transpiling eth-block-tracker, and making this reverse-compatible again.

**Comment by flyswatter** [comment]
We're going to track this in MetaMask too:
https://github.com/MetaMask/metamask-plugin/issues/1337

**Comment by flyswatter** [comment]
Fixed in `web3-provider-engine@12.0.2`. @Moejoe90 @gagarin55 @LogvinovLeon

**Comment by Moejoe90** [comment]
The best option would be to include transpiling in its build process and export that, but that might be tricky. 
Thanks for the quick reply

**Comment by moodysalem** [comment]
This happens with `react-scripts` 1.0.14 and `web3-provider-engine` 13.3.3 when I try to import the `ZeroClientProvider`

```
Failed to minify the code from this file: 

        ./node_modules/web3-provider-engine/dist/ZeroClientProvider.js:30 

Read more here: http://bit.ly/2tRViJ9
```

I'm just using a rawgit script tag for now and accessing window.ZeroClientProvider

```
    <script src="https://cdn.rawgit.com/MetaMask/provider-engine/f39dabd9/dist/ZeroClientProvider.js"
            integrity="sha384-1bhcGKfQdEyjqsWD7rhaxbxPKxU8nPn7hZ4wsgGTpMZdKVC8aTLblsgmE3P0g2Tm"
            crossorigin="anonymous"></script>
```
