### ISSUE TITLE
Filter Subprovider Adds Redundant Filters

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/provider-engine#150]
Multiple calls to `newFilter` with the same parameters will create a new polling process, even if the new filter has identical params.

We should dedupe redundant filters, to avoid creating filter leaks like this.

I think this is a pretty solid first mitigation strategy for https://github.com/MetaMask/eth-block-tracker/issues/21 because even if Web3 doesn't fix their Filter leak, we'll only leak as many filters as get registered by sites the user visits, which have a chance at being much more sustainable.

**Comment by kumavis** [comment]
This can be fixed with the inflight caching!
Should be easy to wrap the new subprovider style with the old one

**Comment by flyswatter** [comment]
Oh, fun!  We did most of this work already! :D

**Comment by chejazi** [comment]
I found the problem I was facing in https://github.com/MetaMask/eth-block-tracker/issues/21, which is likely related to this. In filter.js, the filterIndex is inconsistently converted to hex, which results in filters failing to uninstall properly.

Here it seems to be done correctly, with everything using the hex index: 
https://github.com/MetaMask/provider-engine/blob/master/subproviders/filters.js#L109

Whereas on lines 134 and 156 a combination of hex strings and integers are used as indexes. On my local machine, if I use only hex indexes the filters uninstall correctly and there are no subsequent requests.

**Comment by chejazi** [comment]
Ack? This is a pretty simple fix that will result in big performance gains. No longer an endless queue of filter requests.

Also for reference, here are the lines where the uninstall of the filter fails: https://github.com/MetaMask/provider-engine/blob/master/subproviders/filters.js#L209-L212

**Comment by flyswatter** [comment]
Sorry if you were under some false impression that this wasn't a high priority. This is a top priority right now. I'm addressing it in a couple of different ways. If you have a change that you think will help, please, submit a PR, that would be a lot more helpful than links to lines and what you think should be changed on them.

**Comment by kumavis** [comment]
> On my local machine, if I use only hex indexes the filters uninstall correctly and there are no subsequent requests.
@chejazi yes i see that inconsistency-- can you submit a PR for it?
