### ISSUE TITLE
VmSubprovider does not handle contract creation during eth_call correctly

### ISSUE THREAD

**Issue by area** [MetaMask/provider-engine#166]
I've been trying to establish what's been causing the behaviour described at https://github.com/ethereumjs/testrpc/issues/149, and I think I've tracked it down to here. As noted in the `testrpc` issue, this behaviour is only exhibited by `testrpc`, not `remix`, which uses `ethereumjs-vm` as well, so the underlying problem doesn't seem to lie there.

The difference appears to be that `testrpc` uses the `VmSubprovider` to execute `eth_call`s, whereas `remix` seems to have rolled its own implementation via `vm.stateManager.checkpoint()` and `vm.stateManager.revert()`. 

The odd behaviour arises, I think, because of creating a new hooked VM to run the call against. I *think* when the new contract is created, it is created in the new VM, but when `get_code` is called, because of the hooking, it is run against the old VM that is being kept pristine, and so it doesn't find the code it's supposed to run.

Using `checkpoint()` and `revert()` against `self.engine.manager.state.blockchain.vm.stateManager` in `VmSubprovider.prototype.runVm` solves this issue for me, and tests still pass. What is the purpose behind creating a VM with the state lookup intercepted rather than this approach, which seems to behave correctly?

**Comment by mikeshultz** [comment]
Could this be related to https://github.com/ethereumjs/testrpc/issues/346?  Was also seeing some hinky stuff from `eth_call` but have not yet dug into `provider-engine`.

**Comment by kumavis** [comment]
this seems like a bug in how testrpc was using vmSubprovider. now its ganache and i think its solved this problem. if you think this still needs to be addressed, let me know
