### ISSUE TITLE
Filter provider doesn't honor quantity id

### ISSUE THREAD

**Issue by bhauman** [MetaMask/provider-engine#169]
## Expected Behavior
If I call getFilterChanges with `0x7` id it should work for a filter with an id `0x07`.

## Current Behavior
If one creates a filter and it returns an id with a leading "0" i.e "0x07",
If one subsequently calls `getFilterChanges` with "0x7" it will fail with:
`FilterSubprovider - no filter with that id: 0x7`

## Possible Solution
Test for numeric value equivalence or remove leading "0"'s to test for equality when responding to `getFilterChanges` requests.

Or never create QUANTITY values that have leading zeros.  

## Possible problem
The `intToHex` function creates hex values that have leading zeros. 

According to https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding
A quantity is a hex value that should not have leading zeros.

eth_newFilter returns a QUANTITY
https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-38
eth_getFilterChanges takes a QUANTITY parameter
https://github.com/ethereum/wiki/wiki/JSON-RPC#parameters-42

**Comment by kumavis** [comment]
you are correct
i really hate whoever made this distinction part of the spec

**Comment by kumavis** [comment]
this was fixed. they are now tolerant of both `0x01` and `0x1`
