### ISSUE TITLE
Filters - LogFilter coerces a valid block of 0 to "latest"

### ISSUE THREAD

**Issue by pszabop** [MetaMask/provider-engine#188]
LogFilter coerces a valid block of `0` to `"latest"`.

This causes stuff such as eth.getPastLogs ({fromBlock: 0, toBlock: 'latest'}) to have the unexpected behavior of only returning the latest block's filter entries.  I have tried `"0"` and this returns nothing, the only valid fromBlock value that seems to work is `1`.

I'm uncertain of the dependency tree (it's complicated) but believe this is because I'm using `testrpc` which uses provider-engine (I think).  It doesn't look like this module is used by `web3.js`.

code:  https://github.com/MetaMask/provider-engine/blob/c878e5ac19e061dc3de7f317f5ed4090b3fbd49c/subproviders/filters.js#L332

I note that other implementations such as web3.js implement a check for `undefined` instead of a boolean check like the code above does.

Related issue here:  https://github.com/ethereum/web3.js/issues/1100

**Comment by kumavis** [comment]
fixed here https://github.com/MetaMask/provider-engine/commit/da1cf7f2d0ff83017f82b13a14fd0874958484cc
