### ISSUE TITLE
Add websocket subprovider

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/provider-engine#189]
This would allow push updates, and compatibility with Web3 1.0.

*Updated March 22, 2018 to help potential new contributors make sense of this issue:*

Provider engine is a system for composing middleware objects (which we call `subproviders`) into a potentially complex system for managing the response to a given request object.

ProviderEngine itself is also an [Ethereum Provider, as in web3.currentProvider](https://github.com/ethereum/wiki/wiki/JavaScript-API), so once composed with middleware, it exposes the standard `sendAsync()` method for Ethereum developers to make requests of the [JSON RPC API](https://github.com/ethereum/wiki/wiki/JSON-RPC).

When calling `providerEngine.sendAsync(yourOpts, callbackFunction)`, those options you pass in get passed from one middleware object to the next. [You can see how here](https://github.com/MetaMask/provider-engine/blob/master/index.js#L92-L153).

[As you can see, each provider is passed the same options object, potentially mutating it](https://github.com/MetaMask/provider-engine/blob/master/index.js#L113), and with a pair of callback functions to either end the response immediately, or to pass the options on to the next provider.

To operate as a `subprovider`, an object only needs to expose a `function handleRequest (options, next, end)`, as you can see [here in the fetch subprovider](https://github.com/MetaMask/provider-engine/blob/master/subproviders/fetch.js#L30).

In that function, the `subprovider` can mutate the `options` freely, and then either call the `next()` or `end()` functions.

`next()` is only used by true "middleware" subproviders, to pass the options to the next subprovider. That function will not be needed for this feature.

The `end()` function represents the result that will be returned to the `ProviderEngine` consumer, and should follow the [JavaScript API](https://github.com/ethereum/wiki/wiki/JavaScript-API) specification, including its JSON-RPC style error format.

The [Fetch Subprovider](https://github.com/MetaMask/provider-engine/blob/master/subproviders/fetch.js#L66) is how MetaMask currently talks to an Ethereum node. It uses the `fetch` API, which is pure HTTP, to make requests of whatever RPC it is pointed at.

This issue is to create a similar subprovider, but one that uses [Websockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) instead of HTTP, and uses the [Geth Websocket API](https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB) instead of the usual HTTP-based JSON RPC API. The request/response format should otherwise be basically identical.

## Further Goals

There are other goals that are often associated with this one, which can make it seem more complicated, but are actually separate deliverables.

### Websocket Block Tracker

Right now the way MetaMask keeps track of the current block is also via HTTP, via the [eth-block-tracker](https://www.npmjs.com/package/eth-block-tracker) module. We could definitely also improve performance by moving that over to websockets, or making a websocket version of it.

### Websocket Based Subscriptions

While #207 adds a subprovider for providing the `providerEngine.subscribe()` API, it does this with polling under the hood. This API would be much more performant if its functionality were moved into the websocket subprovider.

**Comment by kumavis** [comment]
Relevant notes here: https://github.com/MetaMask/metamask-extension/issues/2350#issuecomment-353437246

id like to differentiate between:
- subscription support (can be polyfilled over http transport via block-tracker)
- websocket rpc transport

**Comment by benjamincburns** [comment]
@danfinlay & @kumavis I'm working on websockets support for ganache right now, which included updating to the latest provider engine. I'd be all kinds of happy to package up the subscription subprovider I'm writing as a PR.

I have it mostly written already, but I need to do some cleanup/refactoring. Do you have any strong preferences for the way it should be done? At the moment it holds a reference to the `FilterSubprovider` but I'm likely going to nix that and extend that subprovider instead.

At present it works by exposing an `EventEmitter` interface, which emits subscription updates out on the `data` event. This will work fine for a websocket provider, but our server in ganache will need to handle routing the subscriptions accordingly based on their ID, cleaning them up on disconnect, etc.

**Comment by danfinlay** [comment]
I’d defer to @kumavis, but the end subproviders should just pass through requests, allowing server-side filter management, unless a middleware like filter subprovider were before it.

**Comment by pablasso** [comment]
Isn't this already tackled by #207?

**Comment by ryan-rowland** [comment]
Interested in taking a look at this. Looking through the repo, I'm not seeing any tests for `fetchProvider` and I'm having some difficulty getting a minimal test case set up. Can somebody point me to somewhere `fetchProvider` is being included, initialized and used so I can start digging in?

**Comment by lazaridiscom** [comment]
> I'm working on this.

Nice, you picked the more difficult path!

**Comment by ryan-rowland** [comment]
Looking closer at this, it seems there's more to do than just replace FetchProvider with a WebsocketProvider. The provider stack seems to be built around a polling mechanism (using `eth_getBlockByNumber`). To correctly provide websocket support, the information we're receiving from the server should be expected via subscription rather than polling. This means writing a new `subscriptions` subprovider at least. I believe filters and other subproviders may also be built around this assumption of polling.

**Comment by danfinlay** [comment]
@ryan-rowland You are correct, sorry for not including this in the original post (will update it):

Since `provider-engine` is reliant on block-polling, there has been an effort to re-write `provider-engine` without these ethereum-opinionated architectures.

Enter: [json-rpc-engine](https://github.com/kumavis/json-rpc-engine). Basically the same as provider-engine, but without the ethereum-opinionated portions like block-polling.

It would be more correct to write the websocket subprovider for _that_, and then move MetaMask over to it from `provider-engine`.

I'm hoping @kumavis can come in and shed additional light on this, since he's the one who's been re-writing `provider-engine` as `json-rpc-engine`.

**Comment by kumavis** [comment]
@ryan-rowland you added WebsocketSubprovider (thanks!) in https://github.com/MetaMask/provider-engine/pull/227 but did not actually setup forwarding subscription responses (server-sent json rpc 'notifications') on the provider-engine. I did the final steps, and I'm releasing in `14.0.0`

**Comment by kumavis** [comment]
Fixed in `14.0.0`

**Comment by lazaridiscom** [comment]
@kumavis , can you please point to the relevant fixing commit(s) ?

**Comment by lazaridiscom** [comment]
> This would allow push updates, and compatibility with Web3 1.0.

Does this mean that Web3 1.0 is supported ?

**Comment by ryan-rowland** [comment]
Thanks for following up @kumavis ! Glad to see this issue moving forward.

**Comment by lazaridiscom** [comment]
relevant commits, see: https://github.com/MetaMask/provider-engine/pull/227#issuecomment-380148280

**Comment by lazaridiscom** [comment]
@danfinlay , @kumavis , @ryan-rowland - can anyone please inform me (and others following this) what all this here means? Is this a huge step towards web3 1.0 support, or just a tiny one?

**Comment by ryan-rowland** [comment]
@lazaridiscom This adds the logic to talk to the websocket gateways, so it's a step forward. The issue I ran into at this point was getting disconnected from the gateway because the provider was still using polling logic rather than subscription. It seems like @kumavis may have updated the logic to use subscriptions, in which case I'd say this is a big step toward web3 1.0 support.

I'll let @kumavis speak to it in more detail as he's been following up on it.

**Comment by lazaridiscom** [comment]
@ryan-rowland , could you possibly test this here  (me currently off code) :

https://github.com/MetaMask/metamask-extension/issues/3642#issuecomment-380183961

It seems that this provides web3 1.0 support, and me super-curious if this works now.

**Comment by matthewlilley** [comment]
@lazaridiscom @ryan-rowland 

https://github.com/matthewlilley/metamask-extension/commit/6827fdf66581c0ecfa57fab9572f135f5231a681

This is the simplest solution I came up with for providing Web3 1.0+ subscription support to MetaMask, and it's inpage provider. It works. Needs review. @danfinlay @kumavis

**Comment by ryan-rowland** [comment]
@matthewlilley I left comments on your commit. Open a PR next time please. 😄 

@lazaridiscom Sorry I won't be a position to test any time this week.

**Comment by matthewlilley** [comment]
@ryan-rowland https://github.com/MetaMask/metamask-extension/pull/4047

**Comment by jtakalai** [comment]
So... does Metamask now support connecting to custom WS-RPC? If I select Custom RPC and enter New RPC URL that starts with ws://, I get error "URIs require the appropriate HTTP/HTTPS prefix."

**Comment by d10r** [comment]
@jtakalai no, seems to not yet seem the case.  
I guess the issue you need to track is https://github.com/MetaMask/metamask-extension/issues/1645

**Comment by danfinlay** [comment]
Worth noting that MetaMask has converted to a different module we wrote, [json-rpc-engine](https://github.com/MetaMask/json-rpc-engine), which can accomplish the same goals in combination with [eth-json-rpc-middleware](https://github.com/MetaMask/eth-json-rpc-middleware/pull/16).

It is less coupled to the ethereum RPC, and allows a more modular composition of features.

**Comment by lazaridiscom** [comment]
@danfinlay , can you please verify:

My understanding is 

* that a websocket-subprovider was added to metamasks provider-engine (see https://github.com/MetaMask/web3-provider-engine/issues/189#issuecomment-379998858), 

* but that metamask has migrated away from provider-engine to [json-rpc-engine](https://github.com/MetaMask/json-rpc-engine) / [eth-json-rpc-middleware](https://github.com/MetaMask/eth-json-rpc-middleware)

Now, concretely, does this new engine provide support for websockets?

(Possibly the P1 issue https://github.com/MetaMask/metamask-extension/issues/1645 should be updated with the new information / status, or even closed an a new one filed with new information, if too much has changed).

**Comment by danfinlay** [comment]
Yes, a subprovider was added to provider-engine, but it was never added to MetaMask for a few reasons. Moving off provider-engine was more important to allowing performance than websockets (allowed better block-tracker pausing and cache busting by decoupling them from the main engine).

That work could potentially be ported to `json-rpc-engine`, but I'm not sure what else might be needed to get that to work. At the very least, [this file](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/network/createInfuraClient.js) would need to be moved from `eth-json-rpc-infura` to a websocket equivalent, but I think there would also be additional work to allow our current `filter-middleware` (which polyfills subscription behavior with polling) to be deactivated when connected to a websocket source.

There might be other implications, I would ask @kumavis to chime in.
