### ISSUE TITLE
Uncompiled ES6 revisited

### ISSUE THREAD

**Issue by thisbejim** [MetaMask/provider-engine#192]
Some newer javascript features have snuck into the codebase over time since the resolution of this issue: https://github.com/MetaMask/provider-engine/issues/127 

This causes problems when trying to build a [create-react-app](https://github.com/facebookincubator/create-react-app) project that uses provider-engine.

**Comment by kumavis** [comment]
we now publish transpiled bundles + source in `dist` in the published module

**Comment by jetpack3331** [comment]
@kumavis Still get error after using dist/es5 folder

`ERROR in main.xxxx.js from UglifyJs

Unexpected token: name (RpcBlockTracker) [main.xxxx.js:43571,6]`
