### ISSUE TITLE
How do you catch request to <url> failed before engine starts

### ISSUE THREAD

**Issue by Moejoe90** [MetaMask/provider-engine#198]
It is very simple to catch errors after engine starts as you can use 
```
engine.on('error',(err) =>{
});
```
but I am having a challenge catching an error if the couldn't start at all, for example, trying to start with no connection.
For me, it seems that all error handling is done on the basis that there is a connection in the first place. But fails to push the error out of the prototype. 
More specifically here 
```
Web3ProviderEngine.prototype.start = function(){
  const self = this
  // start block polling
  self._blockTracker.start()
}
```

**Comment by kumavis** [comment]
`Web3ProviderEngine.prototype.start` now takes a callback
