### ISSUE TITLE
Filters - SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by andyfo** [MetaMask/provider-engine#201]
Hello!

I am implementing an event getter and watcher in a node.js app like this:

```
contractInstance.MyEventName(null, { fromBlock: 0, toBlock: 'latest' }).get(function(err, result) {
  ...
});

contractInstance.MyEventName(null).watch(function(err, result) {
  ...
});
```

I am connected to Infura through the zero provider engine.

On a testnet (rinkeby), everything works fine.

On the mainnet, I usually (but not always) start getting the JSON SyntaxError periodically  (every few seconds) after calling the watch event:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at asyncify (/path_to_project/node_modules/web3-provider-engine/subproviders/fetch.js:72:34)
    at /path_to_project/node_modules/async/asyncify.js:82:27
    at /path_to_project/node_modules/async/internal/initialParams.js:11:12
    at nextTask (/path_to_project/node_modules/async/waterfall.js:16:14)
    at Immediate.next (/path_to_project/node_modules/async/waterfall.js:23:9)
    at Immediate.<anonymous> (/path_to_project/node_modules/async/internal/onlyOnce.js:12:16)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by Alexnder** [comment]
+1 The same issue on Infura mainnet. It also occurs if there are no any watchers or something.
I mean it takes place if there are just:
```
new Web3(ZeroClientProvider({
      static: {
        eth_syncing: false,
        web3_clientVersion: 'ZeroClientProvider',
      },
      getAccounts: (cb) => cb(null, []),
      rpcUrl: config.data.get('ethProvider')
    }))
```

**Comment by beether** [comment]
I was under the impression that watching an event uses `eth_setFilter`, which is stateful and should not be supported by zero client provider.  I'm surprised it works in the first place.

You should probably use asyncSend "eth_getLogs", and just call this each time you see a new block. It's been foolproof for me.

**Comment by kumavis** [comment]
this is prolly a timeout for too-long request, e.g. `from: 0`
