### ISSUE TITLE
eth_getStorageAt seems to be caching results

### ISSUE THREAD

**Issue by beether** [MetaMask/provider-engine#204]
On Rospten I have a contract deployed.  Index 9 contains a uint of some value that has been set multiple times.

I switch metamask to main, then back to ropsten.

I call: 
`web3.eth.getStorageAt(address, 9, 2311300, callback);`
`web3.eth.getStorageAt(address, 9, 2311600, callback);`

I get the correct results. (0, and 100000000).

Now I do the same to calls.  This time I get back 1000000000 twice.

If I switch to main then back to ropsten again, the same cycle occurs.  It works the first time, but not the second.

Using a regular infura http provider, everything works all the time.

What is going on?

**Comment by beether** [comment]
Just an update.  It appears to cache per: address and storage index.  I did manual calls using .sendAsync() thinking that maybe it was caching by id of a JSONRPC call, but that didn't fix anything.

**Comment by mattotodd** [comment]
seeing this as well

**Comment by kumavis** [comment]
fixed here https://github.com/MetaMask/provider-engine/pull/221
