### ISSUE TITLE
Metamask is unable to fetch data

### ISSUE THREAD

**Issue by tech-somish** [MetaMask/provider-engine#205]
Hi,
For the past few days I have been facing the issue of not getting  data when using **Metamask** as web3 provider in remix. While **Infura** is returning correct data for same contract. I am testing on Kovan testnet.
Below are the screenshots : 

![metamask](https://user-images.githubusercontent.com/33712347/34404533-40a70c38-ebd6-11e7-8ae0-52ff02eac98a.png)

![infura](https://user-images.githubusercontent.com/33712347/34404538-4a9fde2c-ebd6-11e7-889c-2dedabebc03b.png)

Any help would be appreciated. 

Thanks!

**Comment by kumavis** [comment]
Can you be more specific of what data you're requesting, and maybe provide the ABI + kovan contracts for debugging

**Comment by kumavis** [comment]
this seems like a metamask issue, please file over on https://github.com/MetaMask/metamask-extension/issues/new if this is still an issue
