### ISSUE TITLE
Feature request for stateless Web3ProviderEngine

### ISSUE THREAD

**Issue by izetex** [MetaMask/provider-engine#212]
I am using Web3ProviderEngine quite a lot and met the complexities, related to start() / stop() methods and the _blockTracker inside.

There are 2 problems here:

1) controlling the instance of engine appears to be on application. Typical Dapp using web3 just to connect and receive contract interfaces. When using Web3ProviderEngine, in addition i have to control start() and stop() calls. In many cases it is unclear where stop() should be called, as the access to this variable may be already lost

2) additional traffic is generated by block pooling. In mobile application it causes constant traffic
Following these needs, i had to create a simplified provider version: https://github.com/izetex/provider-engine/blob/master/provider.js

Is there a capability to separate Web3ProviderEngine from block pooling at all? 
Simplify provider to a minimum code possible (as i tried to do in https://github.com/izetex/provider-engine/blob/master/provider.js) and extract the current logic to a subprovider

**Comment by daoready** [comment]
In addition what i found that some sub-providers, for example GasProvider, do not use the fact that the provider is statefull. Instead of pre-computation gas price based on engine.onBlock it makes a request for the latest block.

**Comment by izetex** [comment]
Also some sub-providers, for example GaspriceProvide, do not use the fact that the provider is statefull. I think that the state must be maintained in a sub-provider, that will be specially introduced, If it is added to the providers, it will maintain the state and other providers will use it. If not, the provider will be completely stateless

**Comment by kumavis** [comment]
adding block polling to provider-engine was a fundamental mistake i made with this module.
i've started work on a more composable rewrite here:
https://github.com/kumavis/json-rpc-engine
https://github.com/MetaMask/eth-json-rpc-middleware
https://github.com/kumavis/eth-json-rpc-filters
