### ISSUE TITLE
FilterProvider limited by EventEmitter maxListeners?

### ISSUE THREAD

**Issue by yarrumretep** [MetaMask/provider-engine#216]
We are using the ProviderEngine with truffle-contract - works great.  Thank you!

In our application, however, we use a lot of filters (like > 20).  And we are getting the dreaded `possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`

If I go in to the FilterProvider code and set the max listeners on the _ready stoplight, our problem is resolved.

My hypothesis is that when a block comes in and the asyncBlockHandlers are invoked, they are likely calling eth_getFilterChanges which are all calling _ready.await(), thus overflowing the stoplight listener list.

I'd propse that the FilterProvider take an option 'maxFilters' that can be bumped and we set the max listeners to that value || 25 (higher than the default event emitter).

I'll submit a PR shortly.

**Comment by kumavis** [comment]
fixed here https://github.com/MetaMask/provider-engine/pull/217
