### ISSUE TITLE
transpile for distribution?

### ISSUE THREAD

**Issue by yarrumretep** [MetaMask/provider-engine#218]
It appears that the two main entry points ProviderEngine and ZeroClientProvider both get browserified as part of the 'bundle' npm script.  Would it make sense to transpile the subproviders, too?

I am using these components in a React application and the webpack on that end complains that the web3-provider-engine module is exporting non ES-5 code.  Their suggested solution is to ask the library you are using to transpile their releases...  Since it looked like part of the code was being massaged I wondered if it would make sense to do the rest?

**Comment by kumavis** [comment]
we now do this, see `dist` inside the installed npm module
