### ISSUE TITLE
Events are properly detected on ropsten but are not detected on mainnet with metamask.

### ISSUE THREAD

**Issue by win2win** [MetaMask/provider-engine#226]
I have implemented provider-engine and it works great when contract is deployed on ropsten with metamask. The same dapp when switched to mainnet, never returns events 

I have disabled provider-engine and work directly with metamask. 
The dapp is working as expected events are received. 

Any ideas what I could do to fix it or troubleshoot?

**Comment by danfinlay** [comment]
Does this problem go away if you reload the page you're watching (after switching the network in MetaMask?)

To try to investigate this, we would need very specific reproduction steps (lots of Dapps are using events without issue).

Could you provide a reproduction website, or github repository that we could try debugging with?

**Comment by win2win** [comment]
Here is a test page. 
https://node2.coinlaunch.co/html/multitoken.html

In order to test this deployment, you need to click any of the buttons starting with "Deploy..."
e.g. "Deploy Token Only" 

This button will call token factory contract and deploy token contract. 

Restarting doesn't change anything, in fact it always works when switching back to ropsten without browser restarting.  This only causes problem on mainnet. 

Btw. it works if I remove provider-engine and when I just use injected web3 by metamask.

My intention to use provider-engine was to eliminate problems with metamask when events are not returned occasionally, which works fine in other cases but in this specific one when contract factory is called, this doesn't work at all on mainnet.

**Comment by danfinlay** [comment]
Is it possible you just need to use the [filter subprovider](https://github.com/MetaMask/provider-engine/blob/master/zero.js#L37)? Events only work if you use this middleware, since it's a stateful endpoint that Infura does not support.

**Comment by win2win** [comment]
I have another deployment which works well with this setup on mainnet and metamask.  
The difference only is that this one accepts payments and uses contract factory. 

Also I'm initializing filter subprovider.

Here is the portion of the code initializing provider-engine. 


`const ProviderEngine = require('web3-provider-engine')
const CacheSubprovider = require('web3-provider-engine/subproviders/cache.js')
const FilterSubprovider = require('web3-provider-engine/subproviders/filters.js')
const Web3Subprovider = require("web3-provider-engine/subproviders/web3.js");

var provider = (window.web3 && window.web3.currentProvider);



var engine = new ProviderEngine({
  getAccounts: function(){},
  pollingInterval: 1000
  });

  
  
  engine.addProvider(new CacheSubprovider());
  engine.addProvider(new FilterSubprovider());
  engine.addProvider(new Web3Subprovider(provider));

  engine.on('block', function(block) {
    console.log('================================')
    var decimal = (block.number[0] << 16) | (block.number[1] << 8) | block.number[2]
    console.log('BLOCK CHANGED:', '#' + decimal, '0x' + block.hash.toString('hex'))
    console.log('================================')
  })
  engine.start();
  window.web3= new Web3(engine)`

Here is the transaction which event hasn't been caught in the front end. 

https://etherscan.io/tx/0x209a78f3679d73c61b4d0c070150364f19e34dde8fa0c44631c0c234db17ce09

**Comment by win2win** [comment]
I solved the problem although I can only speculate why this works now. 
The token factory created a new Token contract and in the constructor of the Token contract i was calling 
**transferOwnership()** function of **Ownable** contract which Token inherited from so the token could be owned by the caller of the function as opposed to parent contract. 

**transferOwnership()**  also has its own event  **OwnershipTransferred(owner, newOwner);**

My suspicion is that since this event was firing within constructor event, this somewhat had confused either web3 or Metamask and the actual event of the contract creation has been somewhere lost.
