### ISSUE TITLE
 inflight-cache cache formated result cause problem

### ISSUE THREAD

**Issue by joey-he8x** [MetaMask/provider-engine#247]
i'm using provider-engine with web3 v1.0beta34

when I enable inflight-cache and try send a transaction which transfer an ERC20 token to another account, I will get an error caused by txReceipt.status=false.
I debug around and figure out that the actual result of txReceipt is status: 0x1. the first time it was formated to true, and cached by inflight-cache, the second time cache was hit and the formatted result was send to format again. and since web3-core-helper/src/formatters.js#line220: receipt.status = Boolean(parseInt(receipt.status)), so the second time receipt.status become false.

**Comment by joey-he8x** [comment]
I found the problem, in subproviders/inflight-cache.js:33 
solve my problem by passing the copy of result to activeRequestHandlers
activeRequestHandlers.forEach((handler) => handler(err, {...result}))

**Comment by kumavis** [comment]
fixed here https://github.com/MetaMask/provider-engine/pull/301
