### ISSUE TITLE
strategy and api for sync method support

### ISSUE THREAD

**Issue by kumavis** [MetaMask/provider-engine#26]

**Comment by kumavis** [comment]
note: if using a web3 stream-provider to connect to a remote provider-engine, the sync support wouldnt go on the remote provider-engine, but on the stream provider. maybe we should have a separate sync engine? think affects optimal cache positioning

**Comment by kumavis** [comment]
added to the initial release milestone b/c people will ask about this

we dont need a great solution but we need at least an answer to the question

**Comment by axic** [comment]
Is it worth adding support for sync method if it cannot be done via a simple wrapper and it greatly increases complexity or code duplication?

**Comment by kumavis** [comment]
no

but my concern is mostly
> we need at least an answer to the question

**Comment by kumavis** [comment]
sync support was deprecated
