### ISSUE TITLE
Metamask doesnt work with local Parity node

### ISSUE THREAD

**Issue by ETHorHIL** [MetaMask/provider-engine#262]
I am running the latest Parity release on my MBP. When I try using Metamask to switch to localhost 8545, it never ends "Connecting to unknown network". 

I tried using my IPadress or localhost on the custom RPC. And I tried various (fully synched) chains like the mainnet, kovan and my local PoA network. 

Using nettop shows that a connection between between Chrome and 8454 has been established...

A friend of mine has the exact same problem.

**Comment by paymog** [comment]
I'm also seeing this issue when I run parity locally with `parity --config dev --unsafe-expose`.

**Comment by paymog** [comment]
https://ethereum.stackexchange.com/questions/54731/connecting-metamask-with-parity showed me the fix: `parity --config dev --unsafe-expose --jsonrpc-cor=all`

**Comment by kumavis** [comment]
@ETHorHIL sounds Metamask does not do a good job of showing the error message, thanks for the report
