### ISSUE TITLE
14.1.0 Breaks in-browser web sockets connections

### ISSUE THREAD

**Issue by r0kk3rz** [MetaMask/provider-engine#285]
Upon upgrading from 14.0.6 to 14.1.0 we started seeing messages like this in our app

```
[WSProvider] Opening socket... websocket.js:29
Firefox can’t establish a connection to the server at wss://example.endpoint.org/. app.js [WSProvider] 
Socket closed, code 1006 (no reason)
```
The offending change seems to be [this one](https://github.com/MetaMask/provider-engine/commit/902a0dd6fad946e571024810e0f15df0d3ff7236#diff-e81ca7a9c798287f67b9e905eb476fa7R143)

Reverting back to 14.0.6 works as expected, I think we're seeing this issue because we are running fully in a browser and not using the [ws node.js](https://www.npmjs.com/package/ws) module

**Comment by kumavis** [comment]
fixed here https://github.com/MetaMask/provider-engine/pull/297
