### ISSUE TITLE
Cache Improvement

### ISSUE THREAD

**Issue by kumavis** [MetaMask/provider-engine#3]
- [x] breakout into separate file
- [ ] handle in-flight caching ( subsequent requests while actively handling request )
- [x] add cache "roll-off" with option for number of blocks before rolloff
- [ ] handle fork-level caching ( requires fork-detection #4 )

**Comment by tcoulter** [comment]
In flight caching already exists since the pipe can only handle a single request at a time, right?

**Comment by kumavis** [comment]
incorrect - rpcs can happen simultaneously, and you can have 10 requests for the same balance at the same time, and all will miss the cache

**Comment by kumavis** [comment]
split into #29 and #28
