### ISSUE TITLE
New EthereumProvider standard (EIP-1193) breaks this library

### ISSUE THREAD

**Issue by pixelmatrix** [MetaMask/provider-engine#303]
As of web3 1.0.0-beta.38, this library no longer works. They've updated and standardized the EthereumProvider API, and it uses `send()` instead of `sendAsync()`.

The result is that all web3 calls throw an error "synchronous requests not supported".

See: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md

---

The breaking web3 version: https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.38

**Comment by dekz** [comment]
For those in need of a fix or some insight, we recently added some utils to convert providers into something more sane/consistent.

Providers are in a right mess currently, but feel free to re-use or follow along [with this code](https://github.com/0xProject/0x-monorepo/pull/1627/files#diff-3349785d7b782a048f508682b07f8e6a).

**Comment by kumavis** [comment]
@dekz yeah I agree, some poor architectural choices were made at the beginning and are hard to correct
i basically rewrote everything as https://github.com/MetaMask/json-rpc-engine and https://github.com/MetaMask/eth-json-rpc-middleware

**Comment by axic** [comment]
Does that mean this repository is obsolete? If so, it should make sense stating that in the readme.

**Comment by kumavis** [comment]
@pixelmatrix sorry, about that, I dont really use this module (much less web3) and try not to spend time maintaining it. Warned webjs author fabian a few times in the first few years of ethereum development not to make breaking changes to standard APIs but he never listened. 

I reccomend everyone to use ethjs over web3js

we had to work around some shit in metamask to deal with some web3 magic bullshit

https://github.com/MetaMask/metamask-extension/commit/45feb43f306f4b21ef007e0c8897cda384c28fc5

**Comment by kumavis** [comment]
so it summary, this is an issue with web3.js not provider-engine

**Comment by kumavis** [comment]
@axic i dont have an equilavent for the provider-engine/zero yet, so not entirely deprecated. currently working on a major version for provider-engine that moves the subprovider implementations over to the newer stuff.

**Comment by kumavis** [comment]
Ill add that `EIP-1193` status is `Draft` and that I cant advocate for it unless it *requires* backwards compatibiliy

**Comment by pixelmatrix** [comment]
@kumavis totally understand and agree. I originally opened this issue to discuss a path forward, since we rely on this as a dependency of our SDK. Unfortunately we have to continue to offer support for web3.js since some of our customers rely on it. 

It seems like the easiest fix is to just add a "send" method to match, but my concern would be that they may continue to change the API. Another option would be to have the engine inherit from their new base provider class instead of from EventEmitter to keep things in sync with them. A final option would be to wrap the engine in another class that forwards the requests.

Do you have any preference here if we were to submit a PR? We can also just maintain our own fork for now.
