### ISSUE TITLE
Add release tags to github

### ISSUE THREAD

**Issue by Moejoe90** [MetaMask/provider-engine#305]
So far good work on the provider engine.

I would also ask if you can tag your future NPM releases to GitHub so it would be easy to follow the latest changes from version to version.

Its more a request so feel free to close this issue if its something you don't want to do

**Comment by kumavis** [comment]
thanks ill try to remember to do that

**Comment by axic** [comment]
You can add them retroactively, just do `git tag <version> <commithash>` for each version, then push it with `git push --tags` 😉
