### ISSUE TITLE
Block Polling

### ISSUE THREAD

**Issue by kumavis** [MetaMask/provider-engine#4]
- [x] factor out into provider
- [x] currently asking for latest block, should increment from last known block instead
- [x] add parameters for block polling interval
- [ ] fork detection ( emit('fork', lastCommonBlock) )

**Comment by axic** [comment]
This would be really nice to have. I'm currently disabling it manually as it is not needed in my case.

**Comment by SilentCicero** [comment]
Digging this ==DD

**Comment by kumavis** [comment]
https://github.com/MetaMask/eth-block-tracker
all done except fork/reog detection: https://github.com/MetaMask/eth-block-tracker/issues/30
