### ISSUE TITLE
Moving to ethereumjs

### ISSUE THREAD

**Issue by axic** [MetaMask/provider-engine#44]
Do you think it would make sense having this in the ethereumjs project?

**Comment by kumavis** [comment]
yes, this is the plan -- just want to polish it up a bit first before giving it more visibility

**Comment by axic** [comment]
@kumavis any idea what you want to have done before moving?

**Comment by kumavis** [comment]
most important is factoring out polling, but I'd like to refactor so everything just gets passed the raw payload and response objects, and can modify them at will. leaves you with the most modularity.

**Comment by kumavis** [comment]
kinda large refactor

**Comment by kumavis** [comment]
started the refactor! index.js slimmed down nicely.
the new api is interesting.. not 100% comfortable with it yet

https://github.com/MetaMask/provider-engine/pull/69

feedback appreciated

**Comment by kumavis** [comment]
@axic are you still interested in this? i would appreciate help maintaining, but in honesty im moving to a  new set of modules:

adding block polling to provider-engine was a fundamental mistake i made with this module.
i've started work on a more composable rewrite here:
https://github.com/kumavis/json-rpc-engine
https://github.com/MetaMask/eth-json-rpc-middleware
https://github.com/kumavis/eth-json-rpc-filters

**Comment by axic** [comment]
Sorry being late to the party. Does it mean that this repo is deprecated and replaced by `eth-json-rpc-middleware`?
