### ISSUE TITLE
Support selecting which methods to override when adding a provider to the chain

### ISSUE THREAD

**Issue by axic** [MetaMask/provider-engine#50]
The subprovider should receive the list and be able to veto if removing some of those would cause the module useless and/or broken. The veto would be an error message and not a silent force continue.

**Comment by kumavis** [comment]
we no longer track a list - so this would represent a significant shift in the subprovider definition. currently subproviders have complete freedom to handle or skip rpc requests

understanding who handles what is all about positioning of the subproviders in the stack

i vote to close this issue

**Comment by axic** [comment]
My idea would be a simple interface, such as a whitelist or blacklist (array of strings) to the subprovider constructor.

There are (or about to be) providers with overlapping methods.

**Comment by kumavis** [comment]
maybe try to capture it over in https://github.com/MetaMask/provider-engine/issues/31
trying to get our goals together to improve the design over there.

**Comment by kumavis** [comment]
i've started work on a more composable rewrite here:
https://github.com/kumavis/json-rpc-engine
https://github.com/MetaMask/eth-json-rpc-middleware
https://github.com/kumavis/eth-json-rpc-filters

you can specify methods to implement by wrapping in `createScaffoldMiddleware` which is nicely composable
https://github.com/kumavis/json-rpc-engine/blob/master/src/createScaffoldMiddleware.js

```js
createScaffoldMiddleware({
  eth_abc: otherMiddleware(),
  eth_xyz: staticValue,
})
```
