### ISSUE TITLE
batch subprovider

### ISSUE THREAD

**Issue by kumavis** [MetaMask/provider-engine#72]
rebatch requests just before hitting the network - could reduce network load

**Comment by kumavis** [comment]
good idea / bad idea?

**Comment by hitchcott** [comment]
Good idea! Especially useful for listing a bunch of different account balances.

**Comment by kumavis** [comment]
@hitchcott we currently handle batch requests by de-batching them, but do you see value in re-batching them before hitting the network?

**Comment by hitchcott** [comment]
For one , as you mentioned, this might improve performance by reducing number of requests and overall load. It also means that if there's a request throttle on the RPC node, it significantly speeds up loading multiple requests. Also, this would also reduce the number of preflight requests.

Let's say you load a view and trigger requests for 5 account balances - with debounced batching, you go from 10 total requests (5 preflight + 5 actual) down to just 2 (1 preflight + 1 actual), which I imagine would be a significant improvement.

**Comment by hitchcott** [comment]
Actually, I might be misunderstanding what batch is for.

https://github.com/ethereum/wiki/wiki/JavaScript-API#batch-requests

If there are actually less requests, that's great, but if it just ensures they process in series, pretty useless. Let's see...

**Comment by kumavis** [comment]
when correctly configured, it shouldn't perform have pre-flights per request
setting headers (e.g. `Content-Type: application/json`)  can trigger per request pre-flight

anyways it would be pretty trivial to make a subp that re-batches, but i dont need one

**Comment by kumavis** [comment]
decided we didnt need this
