### ISSUE TITLE
estimateGas OOG - needs higher default gasLimit?

### ISSUE THREAD

**Issue by kumavis** [MetaMask/provider-engine#76]
from https://github.com/ethereumjs/testrpc/issues/86

**Comment by kumavis** [comment]
@graup so i opened an issue but dont currently have the cycles to push this forward

here's the relevant parts:
vm subprovider https://github.com/MetaMask/provider-engine/blob/master/subproviders/vm.js#L40-L74
example test https://github.com/MetaMask/provider-engine/blob/master/test/wallet.js

**Comment by kumavis** [comment]
i think that we need to do the `switch(payload.method) {...}` before we run the vm, and fill in different defaults to the txParams based on that.

**Comment by brendan87** [comment]
Quick fix was to modify vm.js line 108 from `gasLimit: txParams.gas || block.header.gasLimit,` to just always take the block header limit i.e. `gasLimit: block.header.gasLimit,`
I realise there must be a reason that the txParams.gas is used, but for our purposes (and whoever else might be stuck and need a hotfix) this seems to work fine.

**Comment by kumavis** [comment]
@brendan87 thats a decent fix and I would merge that. The question is - how does geth handle this case? Do they give you unlimited gas or cap it at the current block's gasLimit or what?

**Comment by brendan87** [comment]
I'd love to send a pull request but I'm failing miserably at pushing a new branch (keep getting a 403 auth error).
Regarding geth's methods - they appear to have an unofficial 1 million gas cap (I encounter problems when running a local private node and sending transactions greater than 1 million but I am not certain if it is geth and not the web3 interface so I haven't posted any issues yet). The official block gas limit is around 4 million but as yet I haven't tested up to this amount due to the issues at 1 mil... =(

**Comment by kumavis** [comment]
we now do `txParams.gas || block.header.gasLimit`
https://github.com/MetaMask/provider-engine/blob/master/subproviders/vm.js#L108

**Comment by flyswatter** [comment]
Btw, @brendan87, the solution to your auth error is to fork the entire repository under your Github account, push your change as a branch to that remote, and then submit a PR from your remote to ours, in this case to our master.

I really can never endorse the book "Pro Git" enough.

**Comment by kumavis** [comment]
published as `7.8.4`

**Comment by graup** [comment]
Just for clarification, is this code really correct?

`
gasLimit: txParams.gas ? ethUtil.addHexPrefix(txParams.gasLimit) : block.header.gasLimit,
`

First it checks for `txParams.gas`, but then uses `txParams.gasLimit`.

**Comment by kumavis** [comment]
@graup good catch

**Comment by kumavis** [comment]
fixed and published as `7.8.5`
