### ISSUE TITLE
Simplify hooked wallet subprovider

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/provider-engine#87]
Right now the `hooked-wallet-subprovider` requires four methods to be implemented:
- sendTransaction
- sign
- approveTx
- approveMsg

The first two are pure equivalents of `web3.eth` methods, and the second two are used to prompt the user for confirmation, and call back with their responses.

This was confusing to a new user of provider-engine, and once I read it, it seemed strange to me, too.

Why not just provide the pure `web3` methods, and let the consumer deal with approving or throwing an error? It seems like this would make the module easier to understand for new users, while making it more flexible, too.

**Comment by agrcrobles** [comment]
Hi there,

Here it is how I implemented HookedWalletEthTxSubprovider,

https://gist.github.com/agrcrobles/d1cabde05fc38cc032336f1dbdbfb4df

Hope that helps, it is `hooked-wallet-ethtx` but can make as a reference

**Comment by kumavis** [comment]
> Why not just provide the pure web3 methods,

if you want to do this, just roll your own subprovider or hook the rpc methods
the hooks you provide to `hooked-wallet-subprovider` are specific to what parts of the tx + message signing flow you want to hook into
theres also a lot more hooking options added since this issue was opened.
