### ISSUE TITLE
eth_getCode caching strategy

### ISSUE THREAD

**Issue by tcoulter** [MetaMask/provider-engine#9]
We should cache `eth_getCode` requests in such a way that:

* all `eth_getCode` requests that specify a block *after* the code was added to the chain hits the cache; and
* all `eth_getCode` requests that specify a block *before* the code was added to the chain return null (possibly cached)
* all null responses don't overwrite the cached versions above

**Comment by kumavis** [comment]
this should be true for all perma cache requests

**Comment by kumavis** [comment]
example of current failure case:

* eth_getCode now
* eth_call that contract at a block before it was deployed

**Comment by tcoulter** [comment]
This should be fixed in #22.
