### ISSUE TITLE
getCompilers 'cb is not defined'

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/provider-engine#98]
https://github.com/MetaMask/provider-engine/blob/4c457fa5f2adc777d6f75571fa567349b51b6f96/subproviders/solc.js#L20

**Comment by flyswatter** [comment]
That should almost definitely be an `end()` call.

**Comment by axic** [comment]
Seems like this was never fixed :)

Though I think it should be just removed given the most of clients don't have `eth.compile` anymore.

**Comment by danfinlay** [comment]
This wasn't fixed? But we merged in the fix by @aakilfernandes. Did that leave something undone?

**Comment by axic** [comment]
Hm, not sure how, but earlier today it showed me `cb`, now it reads `end`, apparently changed in January. Never mind, this issue should be closed then :)

The new issue I raise: it should be just removed for two reasons:
1) none of the clients have it anymore and
2) it uses an ancient solidity version 0.4.2

**Comment by danfinlay** [comment]
Ok, closing in favor of #186.
